CREATE USER 'theroot'@'localhost' IDENTIFIED WITH mysql_native_password AS '***';GRANT ALL PRIVILEGES ON *.* TO 'theroot'@'localhost' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;

ufWUEo(2s%2v*Ox8D(q5zv!CLT8%FrkM)wkSNT#*3ZMn*kuw(V7D6)+6))rZewI9
